name: desc-deed
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.4.6
  - pandas=3.0.3
  - matplotlib=3.11.0
  - plotly=6.9.0
  - dash=4.4.0
  - sacc=2.4
  - jupyter=1.1.1
  - ipykernel=7.3.0
  - pip
  - pip:
      - lsstdesc-dataregistry==1.7.0
